### ISSUE TITLE
Volcanic ash report naming convention

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#139]
## problem ##
Volcanic ash report names appear to be random names.
eg http://staging.realtime.inasafe.org/media/reports/ash/pdf/report_i6bjmOh.pdf

## proposed solution ##
Volcanic ash report names follow a standard convention for the  volcano, date, time, language

cc
@RikkiWeber  @estukriswati  @ivanbusthomi  @gubuntu

**Comment by lucernae** [comment]
Does:
report_<volcano-name>_<YYYYMMDDHHmmSS>_<language>.pdf sounds good?

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - i was thinking of something like:
2017-11-28_0800_WIB_IN.pdf and 2017-11-28_0800_WIB_IN.pdf

where this is yyyy-mm-dd_hhmm_<time zone of event>_language.pdf

If you want to add volcano name I would put it between time zone and language, but maybe this is not necessary. 
yyyy-mm-dd_hhmm_<time zone of event>_<volcano name>_language.pdf

I think we should be quite consistent with all file naming conventions across the realtime products. When we resolve the time stamp and time zone issues in other tickets these will also impact other realtime services and products.
@timlinux may also have some suggestions about file names

**Comment by lucernae** [comment]
Hi @Charlotte-Morgan , for the timezone, I suggests we are using timezone offset like this: +0700. The reasons: we didn't save the timezone as word like 'WIB' but we rather save the offset. So we can't present back into 'WIB' because many timezone can have the same offset. So, using timezone offset is unambigous.

Also, I just realized that we're talking about a different thing. What you shared is the url, but what you really want is the filename. If you're talking about filename, we already use somewhat standardized name like this:

<img width="456" alt="screen shot 2017-12-18 at 06 49 17" src="https://user-images.githubusercontent.com/831865/34085219-a123b94a-e3bf-11e7-9c89-1a2749392260.png">

This occurs when you tried to download the pdf using download button in the table.

<img width="252" alt="screen shot 2017-12-18 at 06 50 51" src="https://user-images.githubusercontent.com/831865/34085237-f06d43ae-e3bf-11e7-9196-fbdee28581e7.png">

Meanwhile, what you shared here is the url:

> eg http://staging.realtime.inasafe.org/media/reports/ash/pdf/report_i6bjmOh.pdf

So, what I would do is to standardized the url (it will not contain that random name). But your requested change will be applied to the filename (when you click download). The url will follow url convention and not that file convention.

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - I think it is a good idea that the report file name is consistent however the user reaches it

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae  - i note that the behaviour for ash is different to that for earthquake. If I click on the report for eq - the url has the 'sensible' file name.  I think the behaviour in eq would be good to use in other hazards if possible

**Comment by lucernae** [comment]
What I mean is, this one here:

> http://staging.realtime.inasafe.org/media/reports/ash/pdf/report_i6bjmOh.pdf

was supposed to be a url for browser. Maybe the suffix `report_i6bjmOh.pdf` here is misleading, so I will omit it and use proper url like this one: `http://staging.realtime.inasafe.org/realtime/ash/report-map/Agung/20171217232200%2B0000/id/`, so user will not think of it as a file, because it was supposed to be opened by a browser and different browser may have different way to present it.
But in most browser, it will open a pdf viewer instead of download, and if you choose to save it, it will have the standard filename.

> Hi @lucernae - i note that the behaviour for ash is different to that for earthquake. If I click on the report for eq - the url has the 'sensible' file name. I think the behaviour in eq would be good to use in other hazards if possible

I actually doesn't like that. It was implemented because there I was asked in the past to make it compatible with BNPB website. Putting filename in url can be misleading, if the filename format changed in the future, and someone uses the old link, the link will be broken. What I propose is to differentiate between url convention and file convention. The url will be in a more standard format (not including random hash name), but it should not include filename. However if the user chooses to download (or save it from browser pdf preview), it will use the standard filename convention. I'm guessing this is what you really want, as long as the filename have standard form when you saved it.

It is possible to put the filename in the url like you want, but I think we have a better way to do this. For example, in Google Drive we can use the same url for a document, even though the filename gets changed now and then, because they didn't put the filename in the url. The url only contains independent id, which in our case is the event id. In Ash, it comes from a combination of event time, timezone, volcano and language. These combination will be structured in the url.
