### ISSUE TITLE
template update to include fatality probablility

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#176]
Aligned with the replication of templates and migration of realtime to version 4: we have a request to enhance the way fatality estimates are presented to include the probability for the estimated range.

Advice from @hadighasemi on the modifications to the template.

[20180129 EQ Realtime Report.pdf](https://github.com/inasafe/inasafe-realtime/files/1684780/20180129.EQ.Realtime.Report.pdf)

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - please focus on the inclusion of the histogram and tweaks to text. I believe the request to show a dashed line for contours over water has been addressed elsewhere. If necessary we can add some text to explain about MMI only relating to ground shaking and not water stirring

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan and @hadighasemi 
This is my attempt at creating the histogram element in QGIS composer which is based on the probability fatality distribution diagram that is used by PAGER report. the value of each diagram can be linked to an attribute table of a layer in QGIS.
![screenshot_3](https://user-images.githubusercontent.com/7351977/35734955-8c5ff37e-0855-11e8-9535-b6d9ff62bd16.png)

@gubuntu and @lucernae - 
according to @dynaryu comment here https://github.com/inasafe/inasafe-realtime/issues/30#issuecomment-315666920 the ITB Bayesian earthquake model is computing the distribution, but since at that moment we didn't support it yet we get the median value (please CMIIW). Now since in this ticket we want to show the distribution, is there any way for me to access that value so that I can add the element to the new earthquake template? If I understand correctly this is the value that I am expecting to see in the attribute table.
![image](https://user-images.githubusercontent.com/7351977/35736357-516636ac-085a-11e8-8a01-d3a01bc70a4d.png)

**Comment by Charlotte-Morgan** [comment]
nice work @ivanbusthomi - will wait for confirmation from @gubuntu that these are the fields required and that they are calculated in all EQ fatality functions (or not).
It would be nice if all functions calculate the same variables so that a single template can support any of the functions ... we need to show on the template which function was used @ivanbusthomi - can you check we have a variable for this or that is written to a key word somewhere :)

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan 
> we need to show on the template which function was used

In the InaSAFE 4.3 we have that stored as a variable in `@earthquake_function`

This morning mas @samnawi and I discussed the option that instead of showing the histogram of fatality distribution based on the range of fatality number, we can show the fatality rate based on the number of MMI. something like this
![image](https://user-images.githubusercontent.com/7351977/35898798-43b7c166-0bfb-11e8-8bd6-97a704539531.png)

note: the interval above doesn't show the actual proportion of each bar since the interval is wat too far for all of them to fit.

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi - fatality rate by MMI  is in the manual and reports. This is not what we want to show on the histogram. I prefer the previous histogram you were working on that matches the pager style report

**Comment by gubuntu** [comment]
@ivanbusthomi yes your first chart is better. Nice work. If that distribution data is indeed available then we should use it like that. @lucernae please comment on whether the Bayes output distribution is available and if not, what it will take to include it in fields that Composer can use as per Ivan's example.

**Comment by Charlotte-Morgan** [comment]
@lucernae - when you have some spare time :) could you please comment on whether the Bayes output distribution is available. If it is I would like the EQ template replication that @ivanbusthomi is working on to include the histogram for realtime 4.x

**Comment by lucernae** [comment]
Hi @Charlotte-Morgan @ivanbusthomi I'm not sure where do you mean it is available. But basically since in 4.x we will use the same codebase, so if it exists already (and able to be created in desktop), then the same template can be used in realtime 4.x.
Now, I think @ismailsunni @Gustry or @myarjunar is the perfect guy to confirm. If these distributions were accessible as qgis-expression in the template or not.

**Comment by ismailsunni** [comment]
As far as I know, we haven't supported this. I never see the fields that @ivanbusthomi put in the comment [above](https://github.com/inasafe/inasafe-realtime/issues/176#issuecomment-362590805) as an InaSAFE's analysis result.

**Comment by lucernae** [comment]
Not implemented.
