### ISSUE TITLE
InaSAFE Realtime EQ template

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#212]
Some suggestions for the template:
* include the event id in the header
* include if this is based on an initial or post processed shake map
* in the nearby places table - use the same alignment for population and intensity - ie both right or both left
* remove event data from inset map - only show location not any other data
* what is happening with the histogram?

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan 
* include event ID in the header
This is my attempt at putting the event ID on the header of the report, I also try putting the source (initial or post-processed) of the shakemap
_this is using the initial shakemap_
![image](https://user-images.githubusercontent.com/7351977/38009598-51192110-327f-11e8-8f4a-9d33151943a9.png)
_this is using the post-processed shakemap_
![image](https://user-images.githubusercontent.com/7351977/38009399-5726fb78-327e-11e8-9ec1-cc5c65b64340.png)

 * alignment in nearby place table
![image](https://user-images.githubusercontent.com/7351977/38009782-41d1541a-3280-11e8-9e28-6960c3860343.png)

* event data from inset map - I am not sure whether I can do this from the template. maybe mas @myarjunar can explain?

* fatalities distribution histogram - as per @ismailsunni comment here https://github.com/inasafe/inasafe-realtime/issues/176#issuecomment-369540716 - once we have the data to do it, it can be easily added.

**Comment by ivanbusthomi** [comment]
additional
* admin boundaries
* airport icon

**Comment by ivanbusthomi** [comment]
@timlinux @ismailsunni @myarjunar @lucernae 
The issue we have with the contour symbology where the label is not centred as shown below:
![image](https://user-images.githubusercontent.com/7351977/38069878-fb43b510-3342-11e8-9bdf-d884d37e21aa.png)

is actually related to the contour geometry issue in https://github.com/inasafe/inasafe/issues/4893. The MMI value is labelled in the _whole interval_ contour, and since there is still a bug in the _whole interval_ contour geometry, the MMI label is not shown in the middle of the half interval. The screenshot below shows what I mean. 
![image](https://user-images.githubusercontent.com/7351977/38069980-898b11ec-3343-11e8-833b-293877e800ca.png)

**Comment by ivanbusthomi** [comment]
All of the issue and suggestions in this ticket have been addressed. Closing this issue

CC @Charlotte-Morgan @ismailsunni
