### ISSUE TITLE
We need to add restart: always to all docker compose files

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#4]
At last it is here (actually I am not sure which version it arrived in), please ensure that

restart: always

is added to every docker-compose file so that we know services are brought up again after a server or docker daemon restart.

https://docs.docker.com/compose/yml/

@rduivenvoorde and @lucernae this probably concerns both of you...

See original ticket at https://github.com/inasafe/inasafe/issues/2212 for further discussion.

**Comment by lucernae** [comment]
We need to be careful to add restart always, as sometimes the problem is not because the container dies. But because the container hangs (stop working but doesn't die).
Also, sometimes the order is important. For example, postgis containers need to be up first and wait for a couple of secs to load the database. If it is accessed by other containers (like Django) before it starts completely, the db container will die then restart (if using auto restart). But Django container won't die and hangs :(, and nginx also not dying (even though it needs restart).
Other alternatives is to restart the whole composition.
Or is there any suggestion to reliably spin it up again in stages?

**Comment by gubuntu** [comment]
Yes I think the whole composition needs to be restarted. Can't you put sleep pauses in docker-composer? And Rancher might also be able to manage this better.

**Comment by lucernae** [comment]
Already done in rancher.
