### ISSUE TITLE
One record per EQ on landing page

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-realtime#73]
On the landing page there should be one record per EQ with more columns (first report and second report)

**Comment by Charlotte-Morgan** [comment]
IMO - this might be good to fix before migration.
@lucernae - is there someone you can delegate this to?

**Comment by lucernae** [comment]
This cannot be done, before we actually processed the second shake (post processed one)

**Comment by Charlotte-Morgan** [comment]
Ok - @timlinux and I looked at the data on the server and we saw that the original shake is being sent with only the grid.xml in a folder named for the event but the post processed shake is still arriving will all the other files, not just the grid.xml.

What do you need to be able to process the second file? Do you need us to ask BMKG to change what they are sharing?

**Comment by lucernae** [comment]
No I mean, it need to wait after I implemented InaSAFE Django and InaSAFE Realtime to be able to process the second shake. The main blocker will be because the shake ID can be the same, but it is a different product and need to be also saved, and InaSAFE Realtime was not designed to do this in the first place. So, there is some big refactor involved.

**Comment by Charlotte-Morgan** [comment]
Action: DMI to ask BMKG for the grid.xml only  for data informed. NOTE this is not a blocker for the current work flow.

**Comment by Charlotte-Morgan** [comment]
I have discussed with @hadighasemi  and he will raise this with BMKG Tsunami team when he is next in Jakarta.

**Comment by gubuntu** [comment]
addressed by #60 and #64
