### ISSUE TITLE
Sunda Slab 7.8 scenario

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe-realtime#83]
DMInnovation is supporting UNOCHA to develop a disaster impact model for a contingency plan in Indonesia.

This is a scenario based on an historical event, the 1699 Batavia earthquake. 
**This scenario is being used to develop a contingency plan. 
This event has not happened.**

## request ##
Kartoza to manually run the scenario (grid.xml) through InaSAFE realtime and generate a 'realtime' report. This report to be returned to DMI.
The event and report should not appear on the realtime web site or in any archives that may mistakenly be misinterpreted as a real event.

## data ##
[SundaSlab7.8_scenario.zip](https://github.com/inasafe/inasafe-realtime/files/901394/SundaSlab7.8_scenario.zip)

## when ##
This week please :)

## cc ##
@RikkiWeber @hadighasemi @ivanbusthomi @samnawi @timlinux

**Comment by lucernae** [comment]
Note that, I had to change the event year to 2017 (after 1900), because the original year (1699) doesn't play niccely with python date format.

[20170314071055-en.pdf](https://github.com/inasafe/inasafe-realtime/files/901444/20170314071055-en.pdf)
![20170314071055-en](https://cloud.githubusercontent.com/assets/831865/24737412/a1562c02-1ab8-11e7-8936-cd4943ef4754.png)


[20170314071055-id.pdf](https://github.com/inasafe/inasafe-realtime/files/901443/20170314071055-id.pdf)
![20170314071055-id](https://cloud.githubusercontent.com/assets/831865/24737413/a5194a86-1ab8-11e7-9744-2608d8a99bfa.png)

**Comment by Charlotte-Morgan** [comment]
that was quick :)  did you also get the contours saved?

**Comment by lucernae** [comment]
This is the MMI output
[mmi_output.zip](https://github.com/inasafe/inasafe-realtime/files/901455/mmi_output.zip)

**Comment by Charlotte-Morgan** [comment]
thank you . @ivanbusthomi - can you grab this, add to minion data and use on your beautiful map please?

**Comment by gubuntu** [comment]
Thanks for beating me to it @lucernae. Nice work. Can we close?

**Comment by lucernae** [comment]
mas @ivanbusthomi please close when it's done.

**Comment by ivanbusthomi** [comment]
@lucernae - sorry I can't close issues in this repository.
:sweat_smile:

**Comment by Charlotte-Morgan** [comment]
thanks everyone
